### ISSUE TITLE
Create clean separation of semantics and styling in Typography components

### ISSUE THREAD

**Issue by petewarman** [dylanaubrey/component-library#34]
We should rename the H1-5 components and allow them to accept a different tag name to render. 

For example rename `H1` to something like `PageTitle`. It should render an `<h1>` by default but should also accept a different tag name to use as a prop - so it can be used like so: 

`<PageTitle tagName="h2">Lorem Ipsum</PageTitle>`

**Comment by dylanaubrey** [comment]
Have picked this up, PR is https://github.com/dylanaubrey/component-library/pull/48
