### ISSUE TITLE
Design & technology documentation 

### ISSUE THREAD

**Issue by jonathanwebster78** [dylanaubrey/component-library#39]
What supporting documentation do we require to enable the successful submission and consumption of a component from the library?

**Comment by jonathanwebster78** [comment]
??? create spec in zeplin that alligns the components more closely with DDL - are they being incorrectly set - organise, categorize & name
Define atoms, molecules etc. -

**Comment by jonathanwebster78** [comment]
Sketch library from Liam should cover the design documentation.
Technical detail should be covered by the documentation Dylan is creating.

**Comment by dylanaubrey** [comment]
I have written a user guide that should be sufficient to start with (we can update as and when required). I am writing a contributing guide (https://github.com/dylanaubrey/component-library/pull/47) and this will be for anyone who wants to contribute or raise a defect, etc. 

In terms of per component usage, each component has documentation that is programmatically generated and can be viewed on each component's package homepage, i.e. https://github.com/dylanaubrey/component-library/tree/master/packages/button.

I would expect this plus the design documentation plus Storybook should be enough.
