### ISSUE TITLE
Tesco Modern Font

### ISSUE THREAD

**Issue by LiamMcMaster1** [dylanaubrey/component-library#50]

**Comment by LiamMcMaster1** [comment]
We need to use the new updated Tesco brand font throughout all our components. This font is not currently used on Tesco.com, GHS or Tesco direct - but is an essential part of alignment to DDL R2 and brand guidelines.

**Comment by dylanaubrey** [comment]
@LiamMcMaster1 and @jonathanwebster78, not sure how big of a priority this is for the component library as the library is font agnostic... it is up to individual websites to start using the font, which these components would inherit... the font is currently installable through the ddl repository... we can make it installable in the same way through the component library... maybe we could look at having it install as part of the default theme...

**Comment by LiamMcMaster1** [comment]
@dylanaubrey @jonathanwebster78, it's very important we use this project to make it as easy as possible for consumers of the library to adopt the new brand. The font is equally important as the colours, the icons etc... i.e. using the font is a non-negotiable, for any Tesco property.

Installing as part of the default theme sounds sensible. Does that mean no work required on individual websites to get the font?

**Comment by dylanaubrey** [comment]
@LiamMcMaster1, websites would still need to include the fonts in their build process for their assets... what I am saying is the fonts are not a component so it should not really sit in the library... 

one thing that could be done, would be hosting the fonts centrally and each website referencing the fonts from this location, so whenever a user navigates between tesco websites they do not have to download the fonts again.... this is not part of the a component library remit, but is something we could discuss with @dobbym when he is back next week.

We could add a font-family value for the tesco modern font as the default and then fall back if they do not have it installed, that is as much as we could do in the theme.

**Comment by dylanaubrey** [comment]
Am picking this up this morning, will consist of two tasks:
- Adding reference to theme for default font of Tesco Modern
- building font into storybook so components have this font by default.

**Comment by dylanaubrey** [comment]
PR raised: https://github.com/dylanaubrey/component-library/pull/63

**Comment by dylanaubrey** [comment]
@LiamMcMaster1 and @jonathanwebster78, I have merged these changes and published packages... 
- so now all components will use the tesco modern font if consumers have the font installed, else they will fall back to arial... 
- I have written the logic to download the fonts as part of using the default theme and the number of font styles to download is configurable by the user.... defaults to no font styles.
- we now just need a location to serve the font from, which Vishal and @dobbym are going to discuss.

**Comment by dylanaubrey** [comment]
Am going to close this issue and raise another specific to setting up shared location to serve fonts from.
