### ISSUE TITLE
To build > Links component

### ISSUE THREAD

**Issue by jonathanwebster78** [dylanaubrey/component-library#51]

**Comment by dylanaubrey** [comment]
Am picking this up based on what has been done before in the ddl libraries and what is on the toolkit website.

https://github.dev.global.tesco.org/ddl-components/ddl-react/blob/master/packages/link
https://github.dev.global.tesco.org/ddl-components/ddl-sass/blob/master/packages/link
https://digital.tesco.org/digital-design-language/toolkit/foundation/link

**Comment by dylanaubrey** [comment]
resolved by #61
