### ISSUE TITLE
To build > Text field

### ISSUE THREAD

**Issue by jonathanwebster78** [dylanaubrey/component-library#52]
Plain and with;
hint 
help 
Optional text field

**Comment by dylanaubrey** [comment]
@jonathanwebster78  and @LiamMcMaster1, what element is this? a text input? what is hint and help? Can you add some more detail to this? We already have an input (https://github.com/dylanaubrey/component-library/blob/master/packages/input) and a input set (https://github.com/dylanaubrey/component-library/blob/master/packages/input-set)

**Comment by jonathanwebster78** [comment]
@dylanaubrey it would be one of these https://digital.tesco.org/digital-design-language/toolkit/elements/form/text_field/view

Do you need more info? Happy to supply :)

**Comment by jonathanwebster78** [comment]
with hint https://digital.tesco.org/digital-design-language/toolkit/elements/form/text_field_hint/view

with help https://digital.tesco.org/digital-design-language/toolkit/elements/form/text_field_help/view

with optional https://digital.tesco.org/digital-design-language/toolkit/elements/form/optioanl_text_field/view

**Comment by dylanaubrey** [comment]
@jonathanwebster78, okay, this is basically the input-set component minus the help link... I am doing the link now and then can integrate that into the input-set component.

**Comment by dylanaubrey** [comment]
@LiamMcMaster1, sure, you can add them here...

**Comment by LiamMcMaster1** [comment]
@dylanaubrey updated the Zeplin to include 'optional' and 'with help link' variations on the label

**Comment by LiamMcMaster1** [comment]
@dylanaubrey amends to match design:
- change text in disabled field to #999999
- Field label should be #333333
- Interactive state should only be triggered on focus, not hover

**Comment by dylanaubrey** [comment]
@LiamMcMaster1 have made the changes and pushed them to master... I have had to add an additional state to the link component because of the way it should display non-bold in the input-set component... will show you and we can discuss.
