### ISSUE TITLE
To build > Checkboxes

### ISSUE THREAD

**Issue by jonathanwebster78** [dylanaubrey/component-library#55]

**Comment by jonathanwebster78** [comment]
Example https://digital.tesco.org/digital-design-language/toolkit/elements/form/checkbox/view

**Comment by dylanaubrey** [comment]
@LiamMcMaster1, what svg should be used for the tick? The success icon we have in the set is not going to work, do you have another one? Also, should the box shadow appear on hover or just on focus like the other elements?
