### ISSUE TITLE
can we support surround property for icon

### ISSUE THREAD

**Issue by murariamar** [dylanaubrey/component-library#75]
can we have support surround property for icon for example to render error icon as in attached image,
need this in submit a review page to display netwrok/api errors
<img width="88" alt="screen shot 2018-05-18 at 5 05 45 pm" src="https://user-images.githubusercontent.com/7846423/40232769-c929d864-5abd-11e8-8c7c-59a346eadba0.png">
<img width="80" alt="screen shot 2018-05-18 at 5 20 22 pm" src="https://user-images.githubusercontent.com/7846423/40233245-d3d3bcd8-5abf-11e8-9c5a-aefbe5823350.png">

**Comment by dylanaubrey** [comment]
@LiamMcMaster1, is this an icon state that is going to be widely used and therefore need to be included in the icon component? ... @murariamar using this and the 'warning' icon for the submit review page as part of an info box at the top of the page.

**Comment by LiamMcMaster1** [comment]
@murariamar @dylanaubrey This isn't something we should build as a property of the icons themselves. 

I do want us to include messaging and alerts, as a distinct set of components, at a later date within the library. At the moment its not finalised for the library.

**Comment by LiamMcMaster1** [comment]
Suggest this is built in isolation for ratings and reviews for now, pulling in the icon itself from the library of course

**Comment by dylanaubrey** [comment]
thanks @LiamMcMaster1... @murariamar, use the icon component from the library and build the rest in lego for now then...
